name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Jalankan setiap 12 jam
  workflow_dispatch: # Bisa dijalankan secara manual
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: snake.svg

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push snake.svg to the output branch
        run: |
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/output; then
            git checkout output
          else
            git checkout --orphan output
          fi
          git add snake.svg
          git commit -m "Update snake animation"
          git push --force origin output
