name: Generate Snake Animation

on:
  schedule:
    - cron: "* */12 * * *"

  workflow_dispatch: # Memungkinkan eksekusi manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: heruu-1
          outputs: dist/snake.svg

      - name: Push Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output  # Hasil animasi disimpan di branch "output"
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
