name: Generate Snake Animation

on:
  push:
    branches:
      - output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Remove untracked files
      run: |
        git clean -fdx

    - name: Checkout output branch
      run: |
        git fetch origin
        git checkout output

    - name: Generate Snake Animation
      run: |
        # Your existing commands to generate the snake animation

    - name: Commit and push changes
      run: |
        git add snake.svg
        git commit -m "Update snake animation"
        git push origin output
